/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import BeanClasses.AccountTypeBean;
import DatabaseManager.DatabaseManager;

/**
 *
 * @author Danish
 */
public class AccountTypeFrame extends javax.swing.JFrame {

    /**
     * Creates new form AccountTypeFrame
     */
    public AccountTypeFrame() {
        initComponents();
        getAccountType();
    }
private void getAccountType(){
	try{
		java.util.Vector v=DatabaseManager.getAccountType();		
                accountsList.setListData(v);
	}catch(Exception e){
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}//end Method 
    private void addAccountType(){
    String accountTypeName=accountTypeNameTextField.getText();
    String remarks=remarksTextArea.getText();

    try{
               	int rows=DatabaseManager.addAccountType(accountTypeName,remarks);
	if(rows>=1){
	        	javax.swing.JOptionPane.showMessageDialog(this,rows+" Records Inserted."); 
		clear();
		getAccountType();				
	}
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}   //end 
private void deleteAccountType(){
    int rows = 0;
    
    Object obj[]=(Object[])accountsList.getSelectedValues();
    for(int i=0; i<obj.length;i++){ 
        AccountTypeBean bean = (AccountTypeBean)obj[i];
        if(bean==null)return;
        try{
           rows += DatabaseManager.deleteAccountType(bean.getAccountTypeId());
            }catch(Exception e){
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
            }
    }//end loop
           if(rows>=1){
           javax.swing.JOptionPane.showMessageDialog(this,rows+"Record Removed.");
           getAccountType();
           clear();
           }


}

private void updateAccountType(){
    String accountTypeName=accountTypeNameTextField.getText();
    String remarks=remarksTextArea.getText();
    int rows = 0;
    
    Object obj[]=(Object[])accountsList.getSelectedValues();
    for(int i=0; i<obj.length;i++){ 
        AccountTypeBean bean = (AccountTypeBean)obj[i];
        if(bean==null)return;
            try{
                rows += DatabaseManager.updateAccountType(bean.getAccountTypeId(),accountTypeName,remarks);
                }catch(Exception e){
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
        } 
    }//end loop
	if(rows>=1){
	    javax.swing.JOptionPane.showMessageDialog(this,rows+" Record Modified.");
	    getAccountType();
	    clear();
        	}
 
}

private void clear(){
   accountTypeIdTextField.setText("");
   accountTypeNameTextField.setText("");
    remarksTextArea.setText("");
}    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accountTypeLabel = new javax.swing.JLabel();
        accountTypeIdLabel = new javax.swing.JLabel();
        accountTypeNameLabel = new javax.swing.JLabel();
        remarksLabel = new javax.swing.JLabel();
        accountTypeIdTextField = new javax.swing.JTextField();
        accountTypeNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        accountsList = new javax.swing.JList();
        accountsLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 1000));
        setPreferredSize(new java.awt.Dimension(2000, 1000));
        getContentPane().setLayout(null);

        accountTypeLabel.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        accountTypeLabel.setText("ACCOUNT TYPE");
        getContentPane().add(accountTypeLabel);
        accountTypeLabel.setBounds(580, 50, 490, 60);

        accountTypeIdLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        accountTypeIdLabel.setText("ACCOUNT TYPE ID");
        getContentPane().add(accountTypeIdLabel);
        accountTypeIdLabel.setBounds(100, 250, 190, 25);

        accountTypeNameLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        accountTypeNameLabel.setText("ACCOUNT TYPE NAME");
        getContentPane().add(accountTypeNameLabel);
        accountTypeNameLabel.setBounds(60, 330, 220, 25);

        remarksLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(170, 420, 101, 25);

        accountTypeIdTextField.setEditable(false);
        accountTypeIdTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(accountTypeIdTextField);
        accountTypeIdTextField.setBounds(320, 240, 100, 40);

        accountTypeNameTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(accountTypeNameTextField);
        accountTypeNameTextField.setBounds(320, 320, 590, 40);

        remarksTextArea.setColumns(20);
        remarksTextArea.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 410, 590, 370);

        accountsList.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        accountsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                accountsListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(accountsList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(930, 250, 258, 530);

        accountsLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        accountsLabel.setText("ACCOUNTS");
        getContentPane().add(accountsLabel);
        accountsLabel.setBounds(930, 220, 110, 25);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(930, 820, 260, 50);

        addButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(320, 820, 120, 50);

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(470, 820, 120, 50);

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(620, 820, 120, 50);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(780, 820, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void accountsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_accountsListValueChanged
    AccountTypeBean bean=(AccountTypeBean)accountsList.getSelectedValue();
   if(bean==null)return;

   accountTypeIdTextField.setText( ""+bean.getAccountTypeId());
   accountTypeNameTextField.setText( bean.getAccountTypeName());
   remarksTextArea.setText( bean.getRemarks()); 
    }//GEN-LAST:event_accountsListValueChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
       addAccountType();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateAccountType();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteAccountType();
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountTypeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountTypeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountTypeIdLabel;
    private javax.swing.JTextField accountTypeIdTextField;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JLabel accountTypeNameLabel;
    private javax.swing.JTextField accountTypeNameTextField;
    private javax.swing.JLabel accountsLabel;
    private javax.swing.JList accountsList;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
