/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import BeanClasses.AccountTypeBean;
import BeanClasses.CustomerBean;
import DatabaseManager.DatabaseManager;
import EnDeCoder.Decoder;
import java.util.Date;

/**
 *
 * @author Danish
 */
public class CustomerFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFrame
     */
    public CustomerFrame() {
        initComponents();
        getCustomer();
    }
private void getCustomer(){
	try{
		java.util.Vector v=DatabaseManager.getCustomer();		
                customersList.setListData(v);
	}catch(Exception e){
		javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
	}
}//end Method 
    private void addCustomer(){
    String firstName=firstNameTextField.getText();;
    String lastName=lastNameTextField.getText();;
    String city=cityTextField.getText();;
    String state=stateTextField.getText();;
    String zipCode=zipCodeTextField.getText();;
    String address=addressTextField.getText();;
    String country=countryTextField.getText();;
    String email=emailTextField.getText();;
    String fax=faxTextField.getText();
    String cellNo=cellNoTextField.getText();
    String dateOfCreate=Decoder.getDateFormat(dateOfCreateDateChooser.getDate());
    String remarks=remarksTextArea.getText();

    try{
               	int rows=DatabaseManager.addCustomer(firstName,lastName,city,state,zipCode,address,country,email,fax,cellNo,dateOfCreate,remarks);
	if(rows>=1){
	        	javax.swing.JOptionPane.showMessageDialog(this,rows+" Records Inserted."); 
		clear();
		getCustomer();				
	}
    }catch(Exception e){
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
    }

}   //end 
private void deleteCustomer(){
    int rows = 0;
    
    Object obj[]=(Object[])customersList.getSelectedValues();
    for(int i=0; i<obj.length;i++){ 
        CustomerBean bean = (CustomerBean)obj[i];
        if(bean==null)return;
        try{
           rows += DatabaseManager.deleteCustomer(bean.getCustomerId());
            }catch(Exception e){
                e.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage()); 
            }
    }//end loop
           if(rows>=1){
           javax.swing.JOptionPane.showMessageDialog(this,rows+"Record Removed.");
           getCustomer();
           clear();
           }


}

private void updateCustomer(){

    String firstName=firstNameTextField.getText();;
    String lastName=lastNameTextField.getText();;
    String city=cityTextField.getText();;
    String state=stateTextField.getText();;
    String zipCode=zipCodeTextField.getText();;
    String address=addressTextField.getText();;
    String country=countryTextField.getText();;
    String email=emailTextField.getText();;
    String fax=faxTextField.getText();
    String cellNo=cellNoTextField.getText();
    String dateOfCreate=Decoder.getDateFormat(dateOfCreateDateChooser.getDate());
    String remarks=remarksTextArea.getText();
    int rows = 0;
    
    Object obj[]=(Object[])customersList.getSelectedValues();
    for(int i=0; i<obj.length;i++){ 
        CustomerBean bean = (CustomerBean)obj[i];
        if(bean==null)return;
            try{
                rows += DatabaseManager.updateCustomer(bean.getCustomerId(),firstName,lastName,city,state,zipCode,address,country,email,fax,cellNo,dateOfCreate,remarks);
                }catch(Exception e){
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,"Error: "+e.getMessage());
        } 
    }//end loop
	if(rows>=1){
	    javax.swing.JOptionPane.showMessageDialog(this,rows+" Record Modified.");
	    getCustomer();
	    clear();
        	}
 
}

private void clear(){
    customerIdTextField.setText("");
    firstNameTextField.setText("");
    lastNameTextField.setText("");
    cityTextField.setText("");
    stateTextField.setText("");
    zipCodeTextField.setText("");
    addressTextField.setText("");
    countryTextField.setText("");
    emailTextField.setText("");
    faxTextField.setText("");
    cellNoTextField.setText("");
    dateOfCreateDateChooser.setDate(null);
    remarksTextArea.setText("");
}     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customerLabel = new javax.swing.JLabel();
        customerIdLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        remarksLabel = new javax.swing.JLabel();
        customerIdTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        customersList = new javax.swing.JList();
        customersLabel = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        lastNameLabel = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        stateTextField = new javax.swing.JTextField();
        zipCodeLabel = new javax.swing.JLabel();
        zipCodeTextField = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        countryLabel = new javax.swing.JLabel();
        countryTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        faxLabel = new javax.swing.JLabel();
        faxTextField = new javax.swing.JTextField();
        dateOfCreateLabel = new javax.swing.JLabel();
        cellNoTextField = new javax.swing.JTextField();
        cellNoLabel = new javax.swing.JLabel();
        dateOfCreateDateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(2000, 1000));
        setPreferredSize(new java.awt.Dimension(2000, 1000));
        getContentPane().setLayout(null);

        customerLabel.setFont(new java.awt.Font("Stencil Std", 1, 60)); // NOI18N
        customerLabel.setText("CusTOMER");
        getContentPane().add(customerLabel);
        customerLabel.setBounds(600, 30, 350, 60);

        customerIdLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        customerIdLabel.setText("CUSTOMER ID");
        getContentPane().add(customerIdLabel);
        customerIdLabel.setBounds(130, 140, 150, 25);

        firstNameLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        firstNameLabel.setText("FIRST NAME");
        getContentPane().add(firstNameLabel);
        firstNameLabel.setBounds(150, 190, 130, 25);

        remarksLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        remarksLabel.setText("REMARKS");
        getContentPane().add(remarksLabel);
        remarksLabel.setBounds(170, 720, 101, 25);

        customerIdTextField.setEditable(false);
        customerIdTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(customerIdTextField);
        customerIdTextField.setBounds(320, 130, 100, 40);

        firstNameTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(firstNameTextField);
        firstNameTextField.setBounds(320, 180, 590, 40);

        remarksTextArea.setColumns(20);
        remarksTextArea.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        remarksTextArea.setRows(5);
        jScrollPane1.setViewportView(remarksTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 710, 590, 130);

        customersList.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        customersList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                customersListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(customersList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(930, 160, 380, 690);

        customersLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        customersLabel.setText("CUSTOMERS");
        getContentPane().add(customersLabel);
        customersLabel.setBounds(930, 130, 130, 25);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        deleteButton.setText("DELETE");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        getContentPane().add(deleteButton);
        deleteButton.setBounds(930, 880, 380, 50);

        addButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addButton);
        addButton.setBounds(320, 880, 120, 50);

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        updateButton.setText("UPDATE");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        getContentPane().add(updateButton);
        updateButton.setBounds(470, 880, 120, 50);

        clearButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton);
        clearButton.setBounds(620, 880, 120, 50);

        backButton.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(780, 880, 120, 50);

        lastNameLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lastNameLabel.setText("LAST NAME");
        getContentPane().add(lastNameLabel);
        lastNameLabel.setBounds(160, 240, 120, 25);

        lastNameTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(lastNameTextField);
        lastNameTextField.setBounds(320, 230, 590, 40);

        cityLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cityLabel.setText("CITY");
        getContentPane().add(cityLabel);
        cityLabel.setBounds(230, 290, 50, 25);

        cityTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(cityTextField);
        cityTextField.setBounds(320, 280, 590, 40);

        stateLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        stateLabel.setText("STATE");
        getContentPane().add(stateLabel);
        stateLabel.setBounds(210, 340, 70, 25);

        stateTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(stateTextField);
        stateTextField.setBounds(320, 330, 590, 40);

        zipCodeLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        zipCodeLabel.setText("ZIP CODE");
        getContentPane().add(zipCodeLabel);
        zipCodeLabel.setBounds(180, 390, 100, 25);

        zipCodeTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(zipCodeTextField);
        zipCodeTextField.setBounds(320, 380, 590, 40);

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        addressLabel.setText("ADDRESS");
        getContentPane().add(addressLabel);
        addressLabel.setBounds(180, 440, 100, 25);

        addressTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(addressTextField);
        addressTextField.setBounds(320, 430, 590, 40);

        countryLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        countryLabel.setText("COUNTRY");
        getContentPane().add(countryLabel);
        countryLabel.setBounds(180, 490, 100, 25);

        countryTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(countryTextField);
        countryTextField.setBounds(320, 480, 590, 40);

        emailLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        emailLabel.setText("EMAIL");
        getContentPane().add(emailLabel);
        emailLabel.setBounds(210, 540, 70, 25);

        emailTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(emailTextField);
        emailTextField.setBounds(320, 530, 590, 40);

        faxLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        faxLabel.setText("FAX");
        getContentPane().add(faxLabel);
        faxLabel.setBounds(230, 590, 50, 25);

        faxTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(faxTextField);
        faxTextField.setBounds(320, 580, 590, 40);

        dateOfCreateLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        dateOfCreateLabel.setText("DATE OF CREATE");
        getContentPane().add(dateOfCreateLabel);
        dateOfCreateLabel.setBounds(500, 650, 180, 25);

        cellNoTextField.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        getContentPane().add(cellNoTextField);
        cellNoTextField.setBounds(320, 640, 160, 40);

        cellNoLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        cellNoLabel.setText("CELL NO");
        getContentPane().add(cellNoLabel);
        cellNoLabel.setBounds(190, 650, 90, 25);
        getContentPane().add(dateOfCreateDateChooser);
        dateOfCreateDateChooser.setBounds(690, 640, 220, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customersListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_customersListValueChanged
        CustomerBean bean=(CustomerBean)customersList.getSelectedValue();
        if(bean==null)return;

    customerIdTextField.setText(""+bean.getCustomerId());
    firstNameTextField.setText(bean.getFirstName());
    lastNameTextField.setText(bean.getLastName());
    cityTextField.setText(bean.getCity());
    stateTextField.setText(bean.getState());
    zipCodeTextField.setText(bean.getZipCode());
    addressTextField.setText(bean.getAddress());
    countryTextField.setText(bean.getCountry());
    emailTextField.setText(bean.getEmail());
    faxTextField.setText(bean.getFax());
    cellNoTextField.setText(bean.getCellNo());
    dateOfCreateDateChooser.setDate(bean.getDateOfCreate());
    remarksTextArea.setText(bean.getRemarks());
    }//GEN-LAST:event_customersListValueChanged

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteCustomer();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addCustomer();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        updateCustomer();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel cellNoLabel;
    private javax.swing.JTextField cellNoTextField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JTextField customerIdTextField;
    private javax.swing.JLabel customerLabel;
    private javax.swing.JLabel customersLabel;
    private javax.swing.JList customersList;
    private com.toedter.calendar.JDateChooser dateOfCreateDateChooser;
    private javax.swing.JLabel dateOfCreateLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel faxLabel;
    private javax.swing.JTextField faxTextField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel remarksLabel;
    private javax.swing.JTextArea remarksTextArea;
    private javax.swing.JLabel stateLabel;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel zipCodeLabel;
    private javax.swing.JTextField zipCodeTextField;
    // End of variables declaration//GEN-END:variables
}
